name: Secrets workflow

on:
  pull_request:
    branches: ["main"]

env:
  API_SCPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"  

jobs:
  secrets:
    name: Secrets demo
    runs-on: ubuntu-latest

    steps:

      - name: echo environment variable
        run: echo $"API_SCPROJ_PATH"
